@extends('layouts.site')
@section('header')
    @include('template.header')
@endsection
@section('content')
    @include('admin.category_edit_content')
@endsection
@section('footer')
    @include('template.footer')
@endsection