@extends('layouts.site')
@section('header')
    @include('template.header')
@endsection
@section('content')
    @include('template.category_content')
@endsection
@section('sidebar')
    @include('template.sidebar')
@endsection
@section('footer')
    @include('template.footer')
@endsection